services:
  database:
    image: postgres:14.3
    container_name: otravel_postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=otravel_db
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
    ports:
      - 5432:5432